version: 2
jobs:
  build_php7:
    docker:
      - image: circleci/php:7.3.1
    steps:
      - checkout
      - run: COMPOSER=composer.json composer install
      - run: COMPOSER=composer.json composer test
      - run: COMPOSER=composer.json composer phpstan
      - run: COMPOSER=composer.json composer lint
  build_php5:
    docker:
      - image: circleci/php:5.6.40-zts-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: COMPOSER=composer.circleci.json composer install
      - run: COMPOSER=composer.circleci.json composer test
workflows:
  version: 2
  build_php_versions:
    jobs:
      - build_php5
      - build_php7
