version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6.40-zts-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: composer install --no-dev
      - run: composer require phpunit
      - run: composer test
