version: 2
jobs:
  build_php7.4:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run: COMPOSER=composer.json composer install
      - run: COMPOSER=composer.json composer test
      - run: COMPOSER=composer.json composer phpstan
      - run: COMPOSER=composer.json composer lint
  build_php7.3:
    docker:
      - image: circleci/php:7.3.1
    steps:
      - checkout
      - run: COMPOSER=composer.json composer install
      - run: COMPOSER=composer.json composer test
      - run: COMPOSER=composer.json composer phpstan
      - run: COMPOSER=composer.json composer lint
  build_php5.6:
    docker:
      - image: circleci/php:5.6.40-zts-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: COMPOSER=composer.circleci.json composer install
      - run: COMPOSER=composer.circleci.json composer test
  build_php5.4:
    docker:
      - image: lavoweb/php-5.4
    steps:
      - run:
          name: PHP version check
          command: php --version
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - checkout
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install dependencies
          command: COMPOSER=composer.circleci.json php composer.phar install
      - run:
          name: Run tests
          command: COMPOSER=composer.circleci.json php composer.phar test
workflows:
  version: 2
  build_php_versions:
    jobs:
      - build_php5.4
      - build_php5.6
      - build_php7.3
      - build_php7.4
